#!/usr/bin/env bash
cachedir=/var/cache/sshdmonitor/
status=("Accepted" "Failed")

if [ -d "$cachedir" ]
then
	journalctl -u sshd > $cachedir/TMP_DATA
else
	mkdir $cachedir
	journalctl -u sshd > $cachedir/TMP_DATA
fi

for s in ${status[@]}; do
	grep $s $cachedir/TMP_DATA > $cachedir/$s
done

/home/rwgoss/dev/bin/app.exe
rm $cachedir/*