#!/usr/bin/env bash
cachedir=/var/cache/sshdmonitor/
tmpdir=/var/tmp/sshdmonitor/
status=("Accepted" "Failed")
dataExtension=_Data

# Checking for needed files and directories
if [ ! -d "$tmpdir" ]
then
	mkdir $tmpdir
fi
if [ ! -d "$cachedir" ]
then
	mkdir $cachedir
fi

for s in ${status[@]}; do
	datafile=${tmpdir}${s}${dataExtension}
	echo $datafile
	if [ ! -f $datafile ]
	then
		touch $datafile
	fi
done 

# Stage data for processing
journalctl -u sshd > ${cachedir}TMP_DATA

for s in ${status[@]}; do
	grep $s ${cachedir}TMP_DATA > ${cachedir}${s}
done

/home/rwgoss/dev/bin/app.exe
